### ISSUE TITLE
Sorry Confused :D

### ISSUE THREAD

**Issue by jyu041** [hikiko4ern/discord-synthwave#1]
Hi! Big fan of this work, but I really do not know how to install it?? It shows on my themes page, but when I enable it, it does not change anything, Im using betterdiscord

**Comment by hikiko4ern** [comment]
Hi! Try to place the content of [this file](https://github.com/hikiko4ern/discord-synthwave/blob/master/dist/bd.css) to the rest on the **Custom CSS** tab, then click **Update** and **Save**.

Also this theme affects only the code blocks. In the screenshot, [Nocturnal](https://betterdiscordlibrary.com/themes/Nocturnal) seems to be the main theme.

**Comment by jyu041** [comment]
can you send me that file again, link is broken

**Comment by hikiko4ern** [comment]
@jyu041 https://github.com/hikiko4ern/discord-synthwave/blob/master/dist/BetterDiscord.css
