### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by bob-carter** [hikiko4ern/discord-synthwave#3]
Doesn't do anything, drop the file in the folder, and enabled it, and it did nothing.

**Comment by hikiko4ern** [comment]
Hi~
Which Discord mod are you using and which file have you tried? If you are using other themes, they may conflict with this. Please list them, if using.

You can also try putting the contents of [this (for BetterDiscord)](https://github.com/hikiko4ern/discord-synthwave/blob/master/dist/BetterDiscord.css) or [this (for EnhancedDiscord)](https://github.com/hikiko4ern/discord-synthwave/blob/master/dist/EnhancedDiscord.css) file in the end of the Custom CSS (or similar) tab.

**Comment by hikiko4ern** [comment]
Closing as stale. Please comment if you are still having this issue and we will consider reopening.
